<html>
<head>
    <title>Ir para o site - Olá Multicom</title>
    <style type="text/css">
        html,body{height:100%;width:100%;margin:0;padding:0;background-color:#404040;font-family: "Raleway", Sans-serif;}
        .main-page{width:100%;height:100%;display:flex;align-items:center;justify-content: center;}
        .container{width:100%;max-width:800px;text-align:center;}

        .logo-olamarketing{max-width:190px;display:block;margin:0 auto 25px auto;}
        .button-link{font-size: 16px;font-weight:700;background-color: #323232;border-radius: 5px 5px 5px 5px;color:#FFF;padding:10px 20px;text-decoration:none;}
        .button-link:hover{background-color: #FFB600;color:#404040;}
        img {-webkit-user-drag: none;-khtml-user-drag: none;-moz-user-drag: none;-o-user-drag: none;user-drag: none;}
    </style>
</head>
<body>
    <main class="main-page">
    <div class="container">

        <h1 class="logo-olamarketing"><img src="https://ola.marketing/wp-content/uploads/2020/06/logo-ola-10-anos.png" alt="Olá Marketing Estratégico" style="max-width:100%;margin:0 auto;"/></h1>
        <a class="button-link" href="<?php echo $website_url; ?>" target="_blank">😀 Ir para o site</a>
        
    </div>
    </main>
</body>
</html>